apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ env.APP_NAME }}
  namespace: ${{ env.OPENSHIFT_NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ env.APP_NAME }}
  template:
    metadata:
      labels:
        app: ${{ env.APP_NAME }}
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
      - name: ${{ env.APP_NAME }}
        image: ${{ steps.push-image.outputs.registry-path }}
        ports:
        - containerPort: 8080