apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{ env.APP_NAME }}
  namespace: ${{ env.OPENSHIFT_NAMESPACE }}
spec:
  to:
    kind: Service
    name: ${{ env.APP_NAME }}
  port:
    targetPort: 8080