apiVersion: v1
kind: Service
metadata:
  name: ${{ env.APP_NAME }}
  namespace: ${{ env.OPENSHIFT_NAMESPACE }}
spec:
  selector:
    app: ${{ env.APP_NAME }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080