apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  namespace: ${OPENSHIFT_NAMESPACE}
spec:
  template:
    spec:
      containers:
        - name: ${APP_NAME}
          image: ${IMAGE_REGISTRY}/${APP_NAME}:${IMAGE_TAGS}
          